Upgrade to new build 0.4.0
crate/croud pull request #299
Opened 2020-09-29 12:53 UTC by mechanomi

another PR to upgrade the docs build

see my comments on https://github.com/crate/crash/pull/341

modified the Mergify config to look like the Crash config

completely replaced the Travis checks with the standard Travis docs tests. this perhaps can replace https://github.com/crate/croud/pull/298

2020-10-06 15:14 UTC, mechanomi commented
this should be changed to use the GitHub action authored by @mfussenegger on https://github.com/crate/crash/pull/341

2020-11-20 15:57 UTC, mechanomi commented
fixes https://github.com/crate/croud/pull/299

2020-11-20 16:06 UTC, mechanomi commented
can I please get a review from a one of the @crate/sysadmins?

additionally, before I can merge this PR, one of the @crate/sysadmins must update the branch protections for `master` like so:

- disable the Travis CI checks
- enable the new GitHub Actions `docs.yml` workflow

the changes made to the `.mergify.yml` can be used as a guide: https://github.com/crate/croud/pull/299/files#diff-6a30e47dd51449847422017b16878889b848f6602ac56d5a2e67ce8a19afade2

2020-11-23 21:09 UTC, mechanomi commented
@chaudum could you please review this? ty!! <3

2020-11-23 21:24 UTC, chaudum requested changes
This PR does not remove the Travis configuration nor does it add the Github Actions workflows as stated in the description of the PR. Not sure if i

2020-11-23 21:24 UTC, chaudum commented on .gitignore
>  docs/.crate-docs-build
This line could be removed, right?

2020-11-23 22:04 UTC, mechanomi commented
@chaudum how embarrassing! my push errored out and I didn't notice. I have rebased and pushed all the changes now, including a fixup that addresses the comment you left

2020-11-24 12:05 UTC, chaudum approved these changes

2020-11-26 16:54 UTC, merged