Implemented support for wide tabular output format, where all fields are displayed
crate/croud pull request #302
Opened 2020-11-19 16:39 UTC by juanpardo

## Summary of the changes / Why this is an improvement

`-o wide` can be used to print the full table rather than the main columns only.

## Checklist

 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

2020-11-19 22:02 UTC, MarkusH reviewed
Overall looks really good already!

2020-11-20 11:48 UTC, juanpardo commented on croud/printer.py
>          self.transforms = transforms
Thanks, I didn't know that was possible, it's great syntactic sugar!

2020-11-20 11:55 UTC, juanpardo commented on croud/printer.py
> +    display_all_columns: Optional[bool] = False
It worked well for normal cases, but then the tests failed at the time of displaying zero result data, where it was printing nothing. After some thought with @christianbader we opted for `wide` to provide the same result as `table` when there are no results to display. That means wiping the keys is not a valid solution anymore so I moved the complexity into the `TableFormatPrinter` and left the `WideTableFormatPrinter` as a configuration class that fully delegates this logic into its parent class.

Given this scenario I think Option 1 suits it better but very curious to read further thoughts on this :)

2020-11-20 14:47 UTC, MarkusH reviewed
Two small cleanups. Looks great!

2020-11-20 14:47 UTC, MarkusH commented on croud/printer.py
>          super().__init__(keys=keys, transforms=transforms)
Since you don't do anything but call `super().__init__(...)` in this method, you don't need the method at all :)

2020-11-20 14:47 UTC, MarkusH commented on croud/printer.py
> +    def __init__(
As for the `TableFormatPrinter`, you don't need the `__init__()` method at all, since you're only calling the super class' method.

2020-11-20 14:47 UTC, MarkusH commented on croud/printer.py
> +    display_all_columns: Optional[bool] = False
Good point!

2020-11-20 17:46 UTC, mechanomi requested changes
please can you update the corresponding parts of the documentation?

e.g., https://github.com/crate/croud/blob/master/docs/configuration.rst#configuration-file-keys

2020-11-21 16:20 UTC, MarkusH commented on croud/printer.py
> +    display_all_columns: bool = False
Sorry, that I missed this during my last review. You don't need a type annotation here, since mypy can derive it from the variable value.

2020-11-21 16:20 UTC, MarkusH commented on croud/printer.py
> +    display_all_columns: bool = True
As above.

2020-11-21 16:20 UTC, MarkusH approved these changes

2020-11-24 08:29 UTC, juanpardo commented
> please can you update the corresponding parts of the documentation?
> 
> e.g., https://github.com/crate/croud/blob/master/docs/configuration.rst#configuration-file-keys

@mechanomi thanks for your feedback.

I got a question on how to introduce this in the documentation, at the moment there is no mention on the argument `-o` at all anywhere in the documentation, but it already existed before this pull request (with options `table`, `json` and `yaml`).
There is a mention of the options on the default-format part of the documentation in `configuration.rst`. I was wondering if in addition to add it to the supported list of default formats I should also add an entry somewhere to describe what the `-o`  argument does. If so, could you give me an example, even from another project? And where should I put this :P

2020-11-24 14:05 UTC, mechanomi commented
yep, good catch, @juanpardo 

I think the following section needs to be updated: https://github.com/crate/croud/blob/master/docs/configuration.rst#configuration-file-keys

the `-o` option appears to be documented in multiple places, all of them in the commands section of the docs. see, for example: https://crate.io/docs/cloud/cli/en/latest/commands/config.html

search "Optional Arguments"

so, all of the "Possible choices" lists that appears every time `-o` is mentioned need updating too

2020-11-25 11:47 UTC, juanpardo commented
> please can you update the corresponding parts of the documentation?
> 
> e.g., https://github.com/crate/croud/blob/master/docs/configuration.rst#configuration-file-keys

Added the documentation bits. Asked Daisy for help on this area. Turns out the other parts of the docs are generated dynamically so it should be sufficient.

2020-11-26 07:38 UTC, chaudum approved these changes
Otherwise looks great!

2020-11-26 07:38 UTC, chaudum commented on croud/organizations/auditlogs/commands.py
> +        transforms={"actor": actor_id_transfor},
Would you mind fixing the name of the transform method?

```suggestion
        transforms={"actor": actor_id_transform},
```

2020-11-26 10:48 UTC, mechanomi commented
@juanpardo ah. interesting. I did not know that. lgtm then

2020-11-26 10:48 UTC, mechanomi approved these changes

2020-11-26 11:02 UTC, juanpardo commented on croud/organizations/auditlogs/commands.py
> +        transforms={"actor": actor_id_transfor},
Nice catch!

2020-11-26 11:15 UTC, MarkusH approved these changes

2020-11-26 11:15 UTC, MarkusH commented on docs/configuration.rst
> +    (default, displays the most important fields), ``wide`` (a table format displaying all fields), ``json``, or ``yaml``. This value is only used if the current
I'd add line breaks to follow the style of the surrounding docs.

2020-11-26 21:06 UTC, chaudum commented
:tada:

2020-11-27 08:38 UTC, merged